version: "3.9"

volumes: # named volumes can be managed easier using docker-compose
  postgres-volume:

services:
  # Postgress ------------------------------------------------------------------------------------------------
  postgres-service:
    image: "postgres:16.0-alpine3.18" # use 15.2 official postgres version on latest version of alpine linux
    container_name: "postgres-container"
    env_file:
      - postgres/Postgres.env # See all the environment variables of postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data/ # persist data even if container shuts down
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
